plugins { id 'com.android.application' }
android {
    namespace 'com.goodwill.m80doctor'
    compileSdk 34
    defaultConfig {
        applicationId 'com.goodwill.machinedoctor.axisprobe'
        minSdk 23
        targetSdk 34
        versionCode 50
        versionName '5.0-axis-program-probe'
    }
    buildTypes {
        debug { debuggable true }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),'proguard-rules.pro'
        }
    }
}